/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class kyotocabinet_Error_XLOGIC */

#ifndef _Included_kyotocabinet_Error_XLOGIC
#define _Included_kyotocabinet_Error_XLOGIC
#ifdef __cplusplus
extern "C" {
#endif
#undef kyotocabinet_Error_XLOGIC_serialVersionUID
#define kyotocabinet_Error_XLOGIC_serialVersionUID -3042686055658047285LL
#undef kyotocabinet_Error_XLOGIC_serialVersionUID
#define kyotocabinet_Error_XLOGIC_serialVersionUID -3387516993124229948LL
#undef kyotocabinet_Error_XLOGIC_serialVersionUID
#define kyotocabinet_Error_XLOGIC_serialVersionUID -7034897190745766939LL
#undef kyotocabinet_Error_XLOGIC_SUCCESS
#define kyotocabinet_Error_XLOGIC_SUCCESS 0L
#undef kyotocabinet_Error_XLOGIC_NOIMPL
#define kyotocabinet_Error_XLOGIC_NOIMPL 1L
#undef kyotocabinet_Error_XLOGIC_INVALID
#define kyotocabinet_Error_XLOGIC_INVALID 2L
#undef kyotocabinet_Error_XLOGIC_NOREPOS
#define kyotocabinet_Error_XLOGIC_NOREPOS 3L
#undef kyotocabinet_Error_XLOGIC_NOPERM
#define kyotocabinet_Error_XLOGIC_NOPERM 4L
#undef kyotocabinet_Error_XLOGIC_BROKEN
#define kyotocabinet_Error_XLOGIC_BROKEN 5L
#undef kyotocabinet_Error_XLOGIC_DUPREC
#define kyotocabinet_Error_XLOGIC_DUPREC 6L
#undef kyotocabinet_Error_XLOGIC_NOREC
#define kyotocabinet_Error_XLOGIC_NOREC 7L
#undef kyotocabinet_Error_XLOGIC_LOGIC
#define kyotocabinet_Error_XLOGIC_LOGIC 8L
#undef kyotocabinet_Error_XLOGIC_SYSTEM
#define kyotocabinet_Error_XLOGIC_SYSTEM 9L
#undef kyotocabinet_Error_XLOGIC_MISC
#define kyotocabinet_Error_XLOGIC_MISC 15L
#ifdef __cplusplus
}
#endif
#endif
