/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class kyotocabinet_Error */

#ifndef _Included_kyotocabinet_Error
#define _Included_kyotocabinet_Error
#ifdef __cplusplus
extern "C" {
#endif
#undef kyotocabinet_Error_serialVersionUID
#define kyotocabinet_Error_serialVersionUID -3042686055658047285LL
#undef kyotocabinet_Error_serialVersionUID
#define kyotocabinet_Error_serialVersionUID -3387516993124229948LL
#undef kyotocabinet_Error_serialVersionUID
#define kyotocabinet_Error_serialVersionUID -7034897190745766939LL
#undef kyotocabinet_Error_SUCCESS
#define kyotocabinet_Error_SUCCESS 0L
#undef kyotocabinet_Error_NOIMPL
#define kyotocabinet_Error_NOIMPL 1L
#undef kyotocabinet_Error_INVALID
#define kyotocabinet_Error_INVALID 2L
#undef kyotocabinet_Error_NOREPOS
#define kyotocabinet_Error_NOREPOS 3L
#undef kyotocabinet_Error_NOPERM
#define kyotocabinet_Error_NOPERM 4L
#undef kyotocabinet_Error_BROKEN
#define kyotocabinet_Error_BROKEN 5L
#undef kyotocabinet_Error_DUPREC
#define kyotocabinet_Error_DUPREC 6L
#undef kyotocabinet_Error_NOREC
#define kyotocabinet_Error_NOREC 7L
#undef kyotocabinet_Error_LOGIC
#define kyotocabinet_Error_LOGIC 8L
#undef kyotocabinet_Error_SYSTEM
#define kyotocabinet_Error_SYSTEM 9L
#undef kyotocabinet_Error_MISC
#define kyotocabinet_Error_MISC 15L
/*
 * Class:     kyotocabinet_Error
 * Method:    codename
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_kyotocabinet_Error_codename
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
