/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class kyotocabinet_MapReduce */

#ifndef _Included_kyotocabinet_MapReduce
#define _Included_kyotocabinet_MapReduce
#ifdef __cplusplus
extern "C" {
#endif
#undef kyotocabinet_MapReduce_XNOLOCK
#define kyotocabinet_MapReduce_XNOLOCK 1L
#undef kyotocabinet_MapReduce_XNOCOMP
#define kyotocabinet_MapReduce_XNOCOMP 256L
/*
 * Class:     kyotocabinet_MapReduce
 * Method:    execute
 * Signature: (Lkyotocabinet/DB;Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_kyotocabinet_MapReduce_execute
  (JNIEnv *, jobject, jobject, jstring, jint);

/*
 * Class:     kyotocabinet_MapReduce
 * Method:    emit
 * Signature: ([B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_kyotocabinet_MapReduce_emit
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
