/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class kyotocabinet_Error_XNOREC */

#ifndef _Included_kyotocabinet_Error_XNOREC
#define _Included_kyotocabinet_Error_XNOREC
#ifdef __cplusplus
extern "C" {
#endif
#undef kyotocabinet_Error_XNOREC_serialVersionUID
#define kyotocabinet_Error_XNOREC_serialVersionUID -3042686055658047285LL
#undef kyotocabinet_Error_XNOREC_serialVersionUID
#define kyotocabinet_Error_XNOREC_serialVersionUID -3387516993124229948LL
#undef kyotocabinet_Error_XNOREC_serialVersionUID
#define kyotocabinet_Error_XNOREC_serialVersionUID -7034897190745766939LL
#undef kyotocabinet_Error_XNOREC_SUCCESS
#define kyotocabinet_Error_XNOREC_SUCCESS 0L
#undef kyotocabinet_Error_XNOREC_NOIMPL
#define kyotocabinet_Error_XNOREC_NOIMPL 1L
#undef kyotocabinet_Error_XNOREC_INVALID
#define kyotocabinet_Error_XNOREC_INVALID 2L
#undef kyotocabinet_Error_XNOREC_NOREPOS
#define kyotocabinet_Error_XNOREC_NOREPOS 3L
#undef kyotocabinet_Error_XNOREC_NOPERM
#define kyotocabinet_Error_XNOREC_NOPERM 4L
#undef kyotocabinet_Error_XNOREC_BROKEN
#define kyotocabinet_Error_XNOREC_BROKEN 5L
#undef kyotocabinet_Error_XNOREC_DUPREC
#define kyotocabinet_Error_XNOREC_DUPREC 6L
#undef kyotocabinet_Error_XNOREC_NOREC
#define kyotocabinet_Error_XNOREC_NOREC 7L
#undef kyotocabinet_Error_XNOREC_LOGIC
#define kyotocabinet_Error_XNOREC_LOGIC 8L
#undef kyotocabinet_Error_XNOREC_SYSTEM
#define kyotocabinet_Error_XNOREC_SYSTEM 9L
#undef kyotocabinet_Error_XNOREC_MISC
#define kyotocabinet_Error_XNOREC_MISC 15L
#ifdef __cplusplus
}
#endif
#endif
