/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class kyotocabinet_ValueIterator */

#ifndef _Included_kyotocabinet_ValueIterator
#define _Included_kyotocabinet_ValueIterator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     kyotocabinet_ValueIterator
 * Method:    next
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_kyotocabinet_ValueIterator_next
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
