/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class kyotocabinet_Error_XMISC */

#ifndef _Included_kyotocabinet_Error_XMISC
#define _Included_kyotocabinet_Error_XMISC
#ifdef __cplusplus
extern "C" {
#endif
#undef kyotocabinet_Error_XMISC_serialVersionUID
#define kyotocabinet_Error_XMISC_serialVersionUID -3042686055658047285LL
#undef kyotocabinet_Error_XMISC_serialVersionUID
#define kyotocabinet_Error_XMISC_serialVersionUID -3387516993124229948LL
#undef kyotocabinet_Error_XMISC_serialVersionUID
#define kyotocabinet_Error_XMISC_serialVersionUID -7034897190745766939LL
#undef kyotocabinet_Error_XMISC_SUCCESS
#define kyotocabinet_Error_XMISC_SUCCESS 0L
#undef kyotocabinet_Error_XMISC_NOIMPL
#define kyotocabinet_Error_XMISC_NOIMPL 1L
#undef kyotocabinet_Error_XMISC_INVALID
#define kyotocabinet_Error_XMISC_INVALID 2L
#undef kyotocabinet_Error_XMISC_NOREPOS
#define kyotocabinet_Error_XMISC_NOREPOS 3L
#undef kyotocabinet_Error_XMISC_NOPERM
#define kyotocabinet_Error_XMISC_NOPERM 4L
#undef kyotocabinet_Error_XMISC_BROKEN
#define kyotocabinet_Error_XMISC_BROKEN 5L
#undef kyotocabinet_Error_XMISC_DUPREC
#define kyotocabinet_Error_XMISC_DUPREC 6L
#undef kyotocabinet_Error_XMISC_NOREC
#define kyotocabinet_Error_XMISC_NOREC 7L
#undef kyotocabinet_Error_XMISC_LOGIC
#define kyotocabinet_Error_XMISC_LOGIC 8L
#undef kyotocabinet_Error_XMISC_SYSTEM
#define kyotocabinet_Error_XMISC_SYSTEM 9L
#undef kyotocabinet_Error_XMISC_MISC
#define kyotocabinet_Error_XMISC_MISC 15L
#ifdef __cplusplus
}
#endif
#endif
