/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class kyotocabinet_Utility */

#ifndef _Included_kyotocabinet_Utility
#define _Included_kyotocabinet_Utility
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     kyotocabinet_Utility
 * Method:    atoi
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_kyotocabinet_Utility_atoi
  (JNIEnv *, jclass, jstring);

/*
 * Class:     kyotocabinet_Utility
 * Method:    atoix
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_kyotocabinet_Utility_atoix
  (JNIEnv *, jclass, jstring);

/*
 * Class:     kyotocabinet_Utility
 * Method:    atof
 * Signature: (Ljava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_kyotocabinet_Utility_atof
  (JNIEnv *, jclass, jstring);

/*
 * Class:     kyotocabinet_Utility
 * Method:    hash_murmur
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_kyotocabinet_Utility_hash_1murmur
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     kyotocabinet_Utility
 * Method:    hash_fnv
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_kyotocabinet_Utility_hash_1fnv
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     kyotocabinet_Utility
 * Method:    levdist
 * Signature: ([B[B)J
 */
JNIEXPORT jlong JNICALL Java_kyotocabinet_Utility_levdist___3B_3B
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

/*
 * Class:     kyotocabinet_Utility
 * Method:    levdist
 * Signature: (Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_kyotocabinet_Utility_levdist__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     kyotocabinet_Utility
 * Method:    remove_files_recursively
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_kyotocabinet_Utility_remove_1files_1recursively
  (JNIEnv *, jclass, jstring);

/*
 * Class:     kyotocabinet_Utility
 * Method:    version
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_kyotocabinet_Utility_version
  (JNIEnv *, jclass);

/*
 * Class:     kyotocabinet_Utility
 * Method:    init_visitor_NOP
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_kyotocabinet_Utility_init_1visitor_1NOP
  (JNIEnv *, jclass);

/*
 * Class:     kyotocabinet_Utility
 * Method:    init_visitor_REMOVE
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_kyotocabinet_Utility_init_1visitor_1REMOVE
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
