# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "kyotocabinet-java"
  s.version = "0.1.0"
  s.platform = "java"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Clayton Wheeler"]
  s.date = "2012-06-26"
  s.description = "Wrapper for Kyoto Cabinet's Java library for use with JRuby, to provide the same interface as the native kyotocabinet-ruby gem for MRI."
  s.email = "cswh@umich.edu"
  s.extensions = ["ext/kyotocabinet-java/configure"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "ext/kyotocabinet-java/.gitignore",
    "ext/kyotocabinet-java/COPYING",
    "ext/kyotocabinet-java/Cursor.java",
    "ext/kyotocabinet-java/DB.java",
    "ext/kyotocabinet-java/Error.java",
    "ext/kyotocabinet-java/FileProcessor.java",
    "ext/kyotocabinet-java/Loader.java",
    "ext/kyotocabinet-java/Makefile.in",
    "ext/kyotocabinet-java/MapReduce.java",
    "ext/kyotocabinet-java/README",
    "ext/kyotocabinet-java/Test.java",
    "ext/kyotocabinet-java/Utility.java",
    "ext/kyotocabinet-java/VCmakefile",
    "ext/kyotocabinet-java/ValueIterator.java",
    "ext/kyotocabinet-java/Visitor.java",
    "ext/kyotocabinet-java/configure.in",
    "ext/kyotocabinet-java/doc/allclasses-frame.html",
    "ext/kyotocabinet-java/doc/allclasses-noframe.html",
    "ext/kyotocabinet-java/doc/constant-values.html",
    "ext/kyotocabinet-java/doc/index-all.html",
    "ext/kyotocabinet-java/doc/index.html",
    "ext/kyotocabinet-java/doc/kyotocabinet/Cursor.html",
    "ext/kyotocabinet-java/doc/kyotocabinet/DB.html",
    "ext/kyotocabinet-java/doc/kyotocabinet/Error.html",
    "ext/kyotocabinet-java/doc/kyotocabinet/FileProcessor.html",
    "ext/kyotocabinet-java/doc/kyotocabinet/MapReduce.html",
    "ext/kyotocabinet-java/doc/kyotocabinet/Test.html",
    "ext/kyotocabinet-java/doc/kyotocabinet/Utility.html",
    "ext/kyotocabinet-java/doc/kyotocabinet/ValueIterator.html",
    "ext/kyotocabinet-java/doc/kyotocabinet/Visitor.html",
    "ext/kyotocabinet-java/doc/kyotocabinet/package-frame.html",
    "ext/kyotocabinet-java/doc/kyotocabinet/package-summary.html",
    "ext/kyotocabinet-java/doc/kyotocabinet/package-tree.html",
    "ext/kyotocabinet-java/doc/overview-summary.html",
    "ext/kyotocabinet-java/doc/overview-tree.html",
    "ext/kyotocabinet-java/doc/package-list",
    "ext/kyotocabinet-java/doc/resources/background.gif",
    "ext/kyotocabinet-java/doc/resources/tab.gif",
    "ext/kyotocabinet-java/doc/resources/titlebar.gif",
    "ext/kyotocabinet-java/doc/resources/titlebar_end.gif",
    "ext/kyotocabinet-java/doc/serialized-form.html",
    "ext/kyotocabinet-java/doc/stylesheet.css",
    "ext/kyotocabinet-java/example/KCDBEX1.java",
    "ext/kyotocabinet-java/example/KCDBEX2.java",
    "ext/kyotocabinet-java/example/Makefile",
    "ext/kyotocabinet-java/kyotocabinet.cc",
    "ext/kyotocabinet-java/kyotocabinet_Cursor.h",
    "ext/kyotocabinet-java/kyotocabinet_DB.h",
    "ext/kyotocabinet-java/kyotocabinet_Error.h",
    "ext/kyotocabinet-java/kyotocabinet_Error_XBROKEN.h",
    "ext/kyotocabinet-java/kyotocabinet_Error_XDUPREC.h",
    "ext/kyotocabinet-java/kyotocabinet_Error_XINVALID.h",
    "ext/kyotocabinet-java/kyotocabinet_Error_XLOGIC.h",
    "ext/kyotocabinet-java/kyotocabinet_Error_XMISC.h",
    "ext/kyotocabinet-java/kyotocabinet_Error_XNOIMPL.h",
    "ext/kyotocabinet-java/kyotocabinet_Error_XNOPERM.h",
    "ext/kyotocabinet-java/kyotocabinet_Error_XNOREC.h",
    "ext/kyotocabinet-java/kyotocabinet_Error_XNOREPOS.h",
    "ext/kyotocabinet-java/kyotocabinet_Error_XSUCCESS.h",
    "ext/kyotocabinet-java/kyotocabinet_Error_XSYSTEM.h",
    "ext/kyotocabinet-java/kyotocabinet_MapReduce.h",
    "ext/kyotocabinet-java/kyotocabinet_Utility.h",
    "ext/kyotocabinet-java/kyotocabinet_ValueIterator.h",
    "ext/kyotocabinet-java/overview.html",
    "kyotocabinet-java.gemspec",
    "lib/kyotocabinet-java.rb",
    "lib/kyotocabinet-java/version.rb"
  ]
  s.homepage = "http://github.com/csw/kyotocabinet-java"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Kyoto Cabinet Java library for JRuby"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.1.3"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_development_dependency(%q<jruby-openssl>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.1.3"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<jruby-openssl>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.1.3"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<jruby-openssl>, [">= 0"])
  end
end

